name: Network Deploy To Azure
on:
  workflow_dispatch:
    inputs:
      subscription_id:
          description: 'Connectivity Subscription Id'
          required: true
          default: ''
      location:
          description: 'Connectivity Deployment Region'
          required: true
          default: 'eastus'
jobs:
  deploy-to-azure:
    name: 'Deploy to Azure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ github.event.inputs.subscription_id }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_location: ${{ github.event.inputs.location }}
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Set Terraform'
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.8
          terraform_wrapper: false

      - name: 'Terraform Init'
        id: init
        working-directory: ./NetworkDeployment
        run: terraform init

      - name: 'Terraform Apply'
        id: apply
        working-directory: ./NetworkDeployment
        run: terraform apply -input=false -auto-approve