name: Platform TF Destroy
on: workflow_dispatch
jobs:
  deploy-to-azure:
    name: 'Destroy Platform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-18.04
    environment:
        name: Dev-Platform
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Set Terraform'
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.8
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Init'
        id: init
        working-directory: ./PlatformDeployment
        run: terraform init

      - name: 'Terraform Destroy'
        id: destroy
        working-directory: ./PlatformDeployment
        run: terraform destroy -auto-approve